jobs:
  include:
    - dist: bionic
      arch: ppc64le
      language: java
      script:
        - javac hello_world.java
        - java HelloWorld
    - dist: bionic
      arch: amd64
      language: java
      script:
        - javac hello_world.java
        - java HelloWorld
    - dist: focal
      arch: ppc64le
      language: java
      script:
        - javac hello_world.java
        - java HelloWorld
    - dist: focal
      arch: amd64
      language: java
      script:
        - javac hello_world.java
        - java HelloWorld
    - dist: xenial
      arch: ppc64le
      language: java
      script:
        - javac hello_world.java
        - java HelloWorld
    - dist: xenial
      arch: amd64
      language: java
      script:
        - javac hello_world.java
        - java HelloWorld
